version: '3'
services:
    mongo:
        image: mongo
        container_name: mongodb
        command: [--auth]
        command: --serviceExecutor adaptive
        restart: always
        stdin_open: true
        tty: true
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - "27017:27017"
        
